# Definiere das Docker-Image für den GitLab Runner

stages:
  - build
#  - test
#  - deploy
cache:
  paths:
    - frontend/node_modules/



react_build:
  stage: build
  image: node:latest
  script:
    - cd frontend
    - echo Installing npm packages
    - npm install 
    - echo Baue die Anwendung
    - CI=false npm run build

backend_build:
  stage: build
  image: python:latest
  script:
    - cd backend
    - pip install -r requirements.txt


#deploy:
#  stage: deploy
#  script:
#   - echo "Deploying..."

