# Definiere das Docker-Image für den GitLab Runner
image: node:latest

stages:
  - build
#  - test
#  - deploy

before_script:
  # Vor jedem Job auszuführende Befehle
  - docker info

react_build:
  stage: build
  script:
    - cd frontend
    - echo Installing npm packages
    - npm install
    - echo Baue die Anwendung
    - npm run build


# variables:
#   CI_NODE_INDEX: "1" 

# cache:
#   key: ${CI_COMMIT_REF_SLUG}
#   paths:
#     - frontend/node_modules/
#     - backend/.venv/  

# react_build:
#   stage: build
#   script:
#     - cd frontend
#     - echo Installing npm packages
#     - npm install
#     - cd Baue die Anwendung
#     - npm run build

#react_test:
#  stage: test
#  script:
#    - cd frontend
#    - echo Installing npm packages
#    - npm install
#    - cd Teste die Anwendung
#    - npm run test

#python_build:
#  stage: build
#  script:
#   - cd backend
#    - pip install -r requirements.txt

#python_test:
#  stage: test
#  script:
#    - cd backend
#   - pip install -r requirements.txt

#deploy:
#  stage: deploy
#  script:
#   - echo "Deploying..."

