# Definiere das Docker-Image für den GitLab Runner

stages:
  - build
  - test
#  - deploy
cache:
  paths:
    - frontend/node_modules/
    - backend/.venv/ 

react_build:
  stage: build
  image: node:latest
  script:
    - cd frontend
    - echo Installiere npm-packages
    - npm install 
    - echo Baue das Frontend
    - CI=false npm run build

react_test:
 stage: test
 script:
   - cd frontend
   - echo Installiere npm-packages
   - npm install
   - echo Teste das Frontend
   - CI=false npm run test

backend_build:
  stage: build
  image: python:latest
  script:
    - cd backend
    - echo Baue das Backend
    - pip install -r requirements.txt

python_test:
  stage: test
  script:
    - cd backend
    - echo Teste das Backend
    # - pip3 install -r requirements.txt  
    # - python3 -m unittest discover -s your_tests_directory -p '*_test.py'


#deploy:
#  stage: deploy
#  script:
#   - echo "Deploying..."

